version: 2.1
orbs:
  cicd: sedstart/cicd@dev:1

jobs:
  invalid-api-key:
    docker:
      - image: cimg/node:25.2.1
    steps:
      - cicd/runcloud:
          api_key: INVALID_KEY
          project_id: 418
          test_id: 1974
          profile_id: 848
          browser: chrome
          headless: true
          environment: QA

workflows:
  invalid-api-key-workflow:
    jobs:
      - invalid-api-key
