version: 2.1
orbs:
  cicd: sedstart/cicd@dev:1

jobs:
  tc02-apiA-project398:
    docker:
      - image: cimg/node:25.2.1
    steps:
      - cicd/runcloud:
          api_key: SEDSTART_API_KEY
          project_id: 398
          test_id: 2170
          profile_id: 900
          browser: chrome
          headless: true
          environment: QA

workflows:
  tc02-workflow:
    jobs:
      - tc02-apiA-project398
