version: 2.1
orbs:
  cicd: sedstart/cicd@dev:1

jobs:
  tc01-valid-project-418:
    docker:
      - image: cimg/node:25.2.1
    steps:
      - cicd/runcloud:
          api_key: SEDSTART_API_KEY
          project_id: 418
          test_id: 2170
          profile_id: 848
          browser: chrome
          headless: true
          environment: QA

workflows:
  tc01-workflow:
    jobs:
      - tc01-valid-project-418

