version: 2.1

orbs:
  sedstart: sedstart/cicd@dev:1

jobs:
  run-sedstart-local-windows:
    resource_class: windows.medium
    machine:
      image: "windows-server-2022-gui:current"
      shell: "powershell.exe -ExecutionPolicy Bypass"
    steps:
      - checkout
      - sedstart/runlocal:
          api_key: SEDSTART_API_KEY_PROD
          project_id: 418
          test_id: 1937
          profile_id: 848
          browser: chrome
          headless: true
          environment: QA

workflows:
  test-workflow:
    jobs:
      - run-sedstart-local-windows
