version: 2.1
orbs:
  cicd: sedstart/cicd@dev:1

jobs:
  invalid-profile-418:
    docker:
      - image: cimg/node:25.2.1
    steps:
      - cicd/runcloud:
          api_key: SEDSTART_API_KEY
          project_id: 418
          test_id: 1974
          profile_id: 9999
          browser: chrome
          headless: true
          environment: default.env

workflows:
  invalid-profile-418-workflow:
    jobs:
      - invalid-profile-418
