version: 2.1
orbs:
  cicd: sedstart/cicd@dev:1
jobs:
  test:
    docker:
      - image: cimg/node:25.2.1
    steps:
      - cicd/runlocal:    
          api_key: SEDSTART_API_KEY      
          project_id: 000
          suite_id: 616
          profile_id: 1141
          browser: chrome
          headless: true
workflows:
  test-workflow:
    jobs:
      - test
