version: 2.1

orbs:
  sedstart: sedstart/cicd@dev:1

jobs:
  run-sedstart-local-mac:
    macos:
      xcode: 16.4.0
    resource_class: m4pro.medium
    steps:
      - checkout
      - sedstart/runlocal:
          api_key: SEDSTART_API_KEY
          project_id: 000
          test_id: 1937
          profile_id: 848
          environment: QA
          browser: "webkit"

workflows:
  test-workflow:
    jobs:
      - run-sedstart-local-mac
